name: e2e

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x
        with:
          build: yarn build
          start: yarn start
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}